INSERT INTO nba_team (name, abbreviation) VALUES
  ('Los Angeles Lakers', 'LAL'),
  ('Golden State Warriors', 'GSW'),
  ('Boston Celtics', 'BOS')
ON DUPLICATE KEY UPDATE
  name = VALUES(name);

INSERT INTO nba_zhiboba_relation_rule_keyword (category, keyword, is_enabled, description) VALUES
  ('block', '盖帽', 1, '封盖/盖帽动作关键词'),
  ('block', '封盖', 1, '封盖/盖帽动作关键词'),
  ('block', '帽', 1, '封盖/盖帽动作关键词'),
  ('block', '大帽', 1, '封盖/盖帽动作关键词'),
  ('steal', '抢断', 1, '抢断动作关键词'),
  ('steal', '断下', 1, '抢断动作关键词'),
  ('steal', '断球', 1, '抢断动作关键词'),
  ('foul', '犯规', 1, '犯规动作关键词'),
  ('turnover', '造成失误', 1, '造成失误动作关键词'),
  ('turnover', '逼出失误', 1, '造成失误动作关键词'),
  ('turnover', '逼失误', 1, '造成失误动作关键词'),
  ('contest', '干扰', 1, '投篮干扰/扑防动作关键词'),
  ('contest', '封到', 1, '投篮干扰/扑防动作关键词'),
  ('contest', '扑防', 1, '投篮干扰/扑防动作关键词'),
  ('score', '命中', 1, '得分结果关键词'),
  ('score', '打进', 1, '得分结果关键词'),
  ('score', '上进', 1, '得分结果关键词'),
  ('score', '抛进', 1, '得分结果关键词'),
  ('score', '投进', 1, '得分结果关键词'),
  ('score', '罚进', 1, '得分结果关键词'),
  ('score', '扣进', 1, '得分结果关键词'),
  ('score', '绝杀', 1, '得分结果关键词'),
  ('score', '补进', 1, '得分结果关键词'),
  ('screen', '挡拆', 1, '掩护/挡拆动作关键词'),
  ('screen', '掩护', 1, '掩护/挡拆动作关键词'),
  ('pass', '递给', 1, '传球动作关键词'),
  ('pass', '分给', 1, '传球动作关键词'),
  ('pass', '分球', 1, '传球动作关键词'),
  ('pass', '分右侧', 1, '传球动作关键词'),
  ('pass', '分左侧', 1, '传球动作关键词'),
  ('pass', '分外线', 1, '传球动作关键词'),
  ('pass', '分底线', 1, '传球动作关键词'),
  ('pass', '分底角', 1, '传球动作关键词'),
  ('pass', '回球', 1, '传球动作关键词'),
  ('pass', '传球', 1, '传球动作关键词'),
  ('pass', '横传', 1, '传球动作关键词'),
  ('pass', '直传', 1, '传球动作关键词'),
  ('pass', '斜传', 1, '传球动作关键词'),
  ('pass', '击地', 1, '传球动作关键词'),
  ('pass', '手递手', 1, '传球动作关键词'),
  ('attack', '对位', 1, '进攻对位/单打动作关键词'),
  ('attack', '面对', 1, '进攻对位/单打动作关键词'),
  ('attack', '单打', 1, '进攻对位/单打动作关键词'),
  ('attack', '强攻', 1, '进攻对位/单打动作关键词'),
  ('attack', '突破', 1, '进攻对位/单打动作关键词'),
  ('attack', '背打', 1, '进攻对位/单打动作关键词'),
  ('rebound', '篮板', 1, '篮板动作关键词'),
  ('rebound', '前场板', 1, '篮板动作关键词'),
  ('rebound', '后场板', 1, '篮板动作关键词'),
  ('help_defense', '协防', 1, '协防/补防动作关键词'),
  ('help_defense', '补防', 1, '协防/补防动作关键词'),
  ('help_defense', '扑防', 1, '协防/补防动作关键词'),
  ('help_defense', '干扰', 1, '协防/补防动作关键词')
ON DUPLICATE KEY UPDATE
  id = id;

INSERT INTO nba_zhiboba_relation_confidence (config_key, confidence, is_enabled, description) VALUES
  ('CONFIDENCE_PASS', 0.6800, 1, '明确传球关系置信度'),
  ('CONFIDENCE_PASS_LOW', 0.6200, 1, '上下文推断传球关系置信度'),
  ('CONFIDENCE_ATTACK', 0.7200, 1, '进攻对位关系置信度'),
  ('CONFIDENCE_STEAL', 0.8500, 1, '抢断关系置信度'),
  ('CONFIDENCE_BLOCK', 0.8800, 1, '封盖关系置信度'),
  ('CONFIDENCE_SCORE_OVER_CONTEST', 0.6600, 1, '协防干扰后得分关系置信度'),
  ('CONFIDENCE_DEFENDS_CONTEST', 0.7000, 1, '协防/干扰防守关系置信度'),
  ('CONFIDENCE_ASSIST', 0.7400, 1, '助攻关系置信度'),
  ('CONFIDENCE_SCORE_OVER', 0.7900, 1, '得分压制防守人关系置信度'),
  ('CONFIDENCE_SCORE_OVER_IMPLICIT', 0.6800, 1, '隐式得分压制关系置信度'),
  ('CONFIDENCE_REBOUND', 0.6100, 1, '篮板关系置信度'),
  ('CONFIDENCE_RULE_FALLBACK', 0.6000, 1, '规则兜底默认置信度')
ON DUPLICATE KEY UPDATE
  id = id;
