CREATE TABLE IF NOT EXISTS nba_team (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  abbreviation VARCHAR(8) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_nba_team_abbr (abbreviation)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS nba_game (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  season VARCHAR(16) NOT NULL,
  game_date DATE NOT NULL,
  home_team_id BIGINT UNSIGNED NOT NULL,
  away_team_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'scheduled',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_nba_game_unique (season, game_date, home_team_id, away_team_id),
  KEY idx_nba_game_date (game_date),
  KEY idx_nba_game_home (home_team_id),
  KEY idx_nba_game_away (away_team_id),
  CONSTRAINT fk_nba_game_home_team FOREIGN KEY (home_team_id) REFERENCES nba_team (id),
  CONSTRAINT fk_nba_game_away_team FOREIGN KEY (away_team_id) REFERENCES nba_team (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS nba_schedule_raw (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source VARCHAR(64) NOT NULL,
  season VARCHAR(16) NOT NULL,
  fetched_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  raw_json JSON NOT NULL,
  PRIMARY KEY (id),
  KEY idx_nba_schedule_raw_season (season),
  KEY idx_nba_schedule_raw_source (source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS nba_store_game_list (
  id VARCHAR(36) NOT NULL COMMENT 'Primary key generated by the sync script',
  game_id VARCHAR(32) NOT NULL COMMENT 'NBA official game id',
  game_date DATE NOT NULL COMMENT 'Game date requested from NBA.com',
  home_name VARCHAR(64) NULL COMMENT 'Home team display name from local team mapping when available',
  visit_name VARCHAR(64) NULL COMMENT 'Away team display name from local team mapping when available',
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Compatibility timestamp used by the old Java table',
  home_team_name_abbr VARCHAR(8) NOT NULL COMMENT 'Lowercase home team tricode',
  visit_team_name_abbr VARCHAR(8) NOT NULL COMMENT 'Lowercase away team tricode',
  `type` VARCHAR(32) NOT NULL DEFAULT 'NBA' COMMENT 'League type',
  home_team_id VARCHAR(32) NULL COMMENT 'NBA official home team id',
  visit_team_id VARCHAR(32) NULL COMMENT 'NBA official away team id',
  source_home_team_name VARCHAR(64) NULL COMMENT 'Home team name returned by NBA.com',
  source_visit_team_name VARCHAR(64) NULL COMMENT 'Away team name returned by NBA.com',
  season_year VARCHAR(16) NULL COMMENT 'NBA season year text',
  season_type VARCHAR(64) NULL COMMENT 'NBA season type text',
  game_status TINYINT NULL COMMENT 'NBA official game status code',
  game_status_text VARCHAR(64) NULL COMMENT 'NBA official game status text',
  game_time_utc DATETIME NULL COMMENT 'Scheduled game time in UTC as returned by NBA.com',
  game_time_eastern DATETIME NULL COMMENT 'Scheduled game time field named Eastern by NBA.com',
  raw_json JSON NULL COMMENT 'Original cardData payload',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row create time',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time',
  PRIMARY KEY (id),
  UNIQUE KEY uk_nba_store_game_list_game_id (game_id),
  KEY idx_nba_store_game_list_game_date (game_date),
  KEY idx_nba_store_game_list_type_date (`type`, game_date),
  KEY idx_nba_store_game_list_home_visit (home_team_name_abbr, visit_team_name_abbr)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='NBA.com official schedule game list';

CREATE TABLE IF NOT EXISTS nba_players_name_data (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  team_id VARCHAR(32) NULL COMMENT 'NBA official team id when available',
  team_name VARCHAR(50) NULL COMMENT 'Team display name',
  player_id VARCHAR(50) NULL COMMENT 'NBA China playerId',
  zhiboba_player_id VARCHAR(50) NOT NULL COMMENT 'Zhiboba player id or generated nba_cn_{player_id}',
  hu_pu_player_id VARCHAR(50) NULL COMMENT 'Hupu player id when available',
  en_player_name VARCHAR(128) NULL COMMENT 'English player name when available',
  nba_player_name VARCHAR(128) NULL COMMENT 'NBA China player name from firstName + lastName or display name',
  zhiboba_player_name VARCHAR(128) NULL COMMENT 'Zhiboba player name',
  player_name_alias VARCHAR(128) NULL COMMENT 'Additional player aliases',
  nba_jersey_number VARCHAR(16) NULL COMMENT 'NBA China jerseyNo',
  zhiboba_jersey_number VARCHAR(16) NULL COMMENT 'Zhiboba jersey number',
  player_code VARCHAR(50) NULL COMMENT 'Player code used for cross-source matching',
  player_salary DECIMAL(15,2) NULL COMMENT 'Player salary when available',
  position_name VARCHAR(64) NULL COMMENT 'Position name',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row create time',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time',
  PRIMARY KEY (id),
  UNIQUE KEY uk_zhiboba_player_id (zhiboba_player_id),
  UNIQUE KEY uk_player_id (player_id),
  KEY idx_team_id (team_id),
  KEY idx_nba_player_code (player_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='NBA player name mapping data';

CREATE TABLE IF NOT EXISTS nba_zhiboba_live_text_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  saishi_id VARCHAR(32) NOT NULL COMMENT 'Game id from Zhiboba or NBA China gameId',
  live_sid BIGINT UNSIGNED NOT NULL COMMENT 'Source event sequence id',
  source VARCHAR(32) NOT NULL DEFAULT 'zhiboba' COMMENT 'Data source: zhiboba or nba_china',
  live_pid VARCHAR(32) NULL COMMENT 'Period id from source',
  pid_text VARCHAR(64) NULL COMMENT 'Period display text',
  live_text LONGTEXT NOT NULL COMMENT 'Original live text',
  segmented_text LONGTEXT NULL COMMENT 'Tokenized live text',
  visit_score INT NULL COMMENT 'Visitor score after event',
  home_score INT NULL COMMENT 'Home score after event',
  user_chn VARCHAR(64) NULL COMMENT 'Player name returned by source',
  current_player_name VARCHAR(128) NULL COMMENT 'Normalized current player name',
  home_score_change INT NULL COMMENT 'Home score delta compared with previous same-source event',
  visit_score_change INT NULL COMMENT 'Visitor score delta compared with previous same-source event',
  score_team_side VARCHAR(16) NULL COMMENT 'Scoring side: home, visit, both or null',
  score_points INT NULL COMMENT 'Points scored by this event',
  score_diff INT NULL COMMENT 'Home score minus visitor score',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row create time',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time',
  PRIMARY KEY (id),
  UNIQUE KEY uk_live_source_sid (source, live_sid),
  KEY idx_saishi_id (saishi_id),
  KEY idx_live_text_source (source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Live text events from Zhiboba and NBA China';

CREATE TABLE IF NOT EXISTS nba_zhiboba_player_relation (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  saishi_id VARCHAR(32) NOT NULL COMMENT 'Game id from source',
  evidence_event_id BIGINT UNSIGNED NOT NULL COMMENT 'nba_zhiboba_live_text_event.id',
  live_sid BIGINT UNSIGNED NOT NULL COMMENT 'Source event sequence id',
  source VARCHAR(32) NOT NULL DEFAULT 'zhiboba' COMMENT 'Data source: zhiboba or nba_china',
  relation_type VARCHAR(64) NOT NULL COMMENT 'Semantic relation type',
  relation_side VARCHAR(16) NOT NULL COMMENT 'Relation side: offense or defense',
  subject_player_name VARCHAR(128) NOT NULL COMMENT 'Subject player name',
  subject_team_id VARCHAR(32) NULL COMMENT 'Subject team id',
  subject_team_name VARCHAR(64) NULL COMMENT 'Subject team name',
  subject_team_side VARCHAR(16) NULL COMMENT 'Subject team side: home or visit',
  subject_team_score INT NULL COMMENT 'Subject team score at event time',
  object_player_name VARCHAR(128) NOT NULL COMMENT 'Object player name',
  object_team_id VARCHAR(32) NULL COMMENT 'Object team id',
  object_team_name VARCHAR(64) NULL COMMENT 'Object team name',
  object_team_side VARCHAR(16) NULL COMMENT 'Object team side: home or visit',
  object_team_score INT NULL COMMENT 'Object team score at event time',
  offense_team_id VARCHAR(32) NULL COMMENT 'Current offense team id',
  offense_team_name VARCHAR(64) NULL COMMENT 'Current offense team name',
  offense_team_side VARCHAR(16) NULL COMMENT 'Current offense side',
  offense_team_score INT NULL COMMENT 'Current offense score',
  offense_team_points INT NULL COMMENT 'Points scored by current offense event',
  possession_number INT NULL COMMENT 'Inferred possession sequence number',
  home_score INT NULL COMMENT 'Home score at event time',
  visit_score INT NULL COMMENT 'Visitor score at event time',
  action_text VARCHAR(128) NULL COMMENT 'Action evidence text',
  result_text VARCHAR(128) NULL COMMENT 'Result evidence text',
  score_points INT NULL COMMENT 'Relation score points',
  evidence_text LONGTEXT NOT NULL COMMENT 'Original evidence text',
  segmented_text LONGTEXT NULL COMMENT 'Tokenized evidence text',
  extractor_name VARCHAR(64) NOT NULL DEFAULT 'siamese_uie' COMMENT 'Extractor name',
  confidence DECIMAL(5,4) NOT NULL DEFAULT 0.5000 COMMENT 'Confidence score from 0 to 1',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row create time',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time',
  PRIMARY KEY (id),
  UNIQUE KEY uk_relation_source_unique (source, saishi_id, evidence_event_id, relation_type, subject_player_name, object_player_name),
  KEY idx_relation_game (saishi_id),
  KEY idx_relation_source (source),
  KEY idx_relation_live_sid (live_sid),
  KEY idx_relation_subject (subject_player_name),
  KEY idx_relation_object (object_player_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Semantic player relations extracted from live text events';

CREATE TABLE IF NOT EXISTS nba_live_text_event (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  game_id BIGINT UNSIGNED NOT NULL,
  source VARCHAR(64) NOT NULL,
  event_time TIMESTAMP NULL,
  quarter TINYINT NULL,
  clock VARCHAR(16) NULL,
  text LONGTEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_live_text_game (game_id),
  KEY idx_live_text_source (source),
  FULLTEXT KEY ftx_live_text (text),
  CONSTRAINT fk_live_text_game FOREIGN KEY (game_id) REFERENCES nba_game (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS nba_live_text_token (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  live_event_id BIGINT UNSIGNED NOT NULL,
  token VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_live_token_event (live_event_id),
  KEY idx_live_token_token (token),
  CONSTRAINT fk_live_token_event FOREIGN KEY (live_event_id) REFERENCES nba_live_text_event (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS nba_semantic_relation (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  game_id BIGINT UNSIGNED NOT NULL,
  subject VARCHAR(256) NOT NULL,
  predicate VARCHAR(128) NOT NULL,
  object VARCHAR(256) NOT NULL,
  evidence_live_event_id BIGINT UNSIGNED NULL,
  confidence DECIMAL(5,4) NOT NULL DEFAULT 0.5000,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_semantic_game (game_id),
  KEY idx_semantic_spo (subject, predicate, object),
  KEY idx_semantic_evidence (evidence_live_event_id),
  CONSTRAINT fk_semantic_game FOREIGN KEY (game_id) REFERENCES nba_game (id),
  CONSTRAINT fk_semantic_evidence FOREIGN KEY (evidence_live_event_id) REFERENCES nba_live_text_event (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS nba_zhiboba_relation_rule_keyword (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  category VARCHAR(64) NOT NULL COMMENT '关键词分类，如 pass/block/score',
  keyword VARCHAR(64) NOT NULL COMMENT '中文触发关键词',
  is_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0禁用',
  description VARCHAR(255) NULL COMMENT '配置说明',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_relation_rule_keyword (category, keyword),
  KEY idx_relation_rule_keyword_category_enabled (category, is_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='球员关系规则关键词配置表';

CREATE TABLE IF NOT EXISTS nba_zhiboba_relation_confidence (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  config_key VARCHAR(64) NOT NULL COMMENT '置信度配置键，如 CONFIDENCE_PASS',
  confidence DECIMAL(5,4) NOT NULL COMMENT '置信度，范围0.0000到1.0000',
  is_enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0禁用',
  description VARCHAR(255) NULL COMMENT '配置说明',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_relation_confidence_key (config_key),
  KEY idx_relation_confidence_enabled (is_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='球员关系抽取置信度配置表';
